name: Publish to GH Pages
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: ${{ github.event.inputs.hugoVersion || '0.112.4' }}
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.128.0/hugo_extended_0.128.0_linux-amd64.tar.gz'
          tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo                    
      - name: Build
        run: ${RUNNER_TEMP}/hugo
      - name: Prepare Deployment Directory
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/built-site

      - name: Copy Files to Deployment Directory
        run: |
          cp -R ${GITHUB_WORKSPACE}/public/* ${GITHUB_WORKSPACE}/built-site/

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          cd ${GITHUB_WORKSPACE}/built-site
          git config user.name 'Yuchen20'  # Replace with your GitHub username
          git config user.email 'yuchenmao2024@163.com'  # Replace with your email
          git add .
          git commit -m 'Updated site'
          git push origin main  # Push to the 'main' branch or your configured branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}